/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.parser;

import caju.node.*;
import caju.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTReservadaCaractere(@SuppressWarnings("unused") TReservadaCaractere node)
    {
        this.index = 0;
    }

    @Override
    public void caseTReservadaBooleano(@SuppressWarnings("unused") TReservadaBooleano node)
    {
        this.index = 1;
    }

    @Override
    public void caseTReservadaNumero(@SuppressWarnings("unused") TReservadaNumero node)
    {
        this.index = 2;
    }

    @Override
    public void caseTReservadaVetor(@SuppressWarnings("unused") TReservadaVetor node)
    {
        this.index = 3;
    }

    @Override
    public void caseTReservadaRetorne(@SuppressWarnings("unused") TReservadaRetorne node)
    {
        this.index = 4;
    }

    @Override
    public void caseTReservadaVazio(@SuppressWarnings("unused") TReservadaVazio node)
    {
        this.index = 5;
    }

    @Override
    public void caseTReservadaInicio(@SuppressWarnings("unused") TReservadaInicio node)
    {
        this.index = 6;
    }

    @Override
    public void caseTReservadaFim(@SuppressWarnings("unused") TReservadaFim node)
    {
        this.index = 7;
    }

    @Override
    public void caseTReservadaSe(@SuppressWarnings("unused") TReservadaSe node)
    {
        this.index = 8;
    }

    @Override
    public void caseTReservadaSenao(@SuppressWarnings("unused") TReservadaSenao node)
    {
        this.index = 9;
    }

    @Override
    public void caseTReservadaEnquanto(@SuppressWarnings("unused") TReservadaEnquanto node)
    {
        this.index = 10;
    }

    @Override
    public void caseTReservadaPara(@SuppressWarnings("unused") TReservadaPara node)
    {
        this.index = 11;
    }

    @Override
    public void caseTReservadaParaCada(@SuppressWarnings("unused") TReservadaParaCada node)
    {
        this.index = 12;
    }

    @Override
    public void caseTReservadaExibir(@SuppressWarnings("unused") TReservadaExibir node)
    {
        this.index = 13;
    }

    @Override
    public void caseTReservadaLer(@SuppressWarnings("unused") TReservadaLer node)
    {
        this.index = 14;
    }

    @Override
    public void caseTIdentificador(@SuppressWarnings("unused") TIdentificador node)
    {
        this.index = 15;
    }

    @Override
    public void caseTCaractere(@SuppressWarnings("unused") TCaractere node)
    {
        this.index = 16;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 17;
    }

    @Override
    public void caseTBooleano(@SuppressWarnings("unused") TBooleano node)
    {
        this.index = 18;
    }

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 19;
    }

    @Override
    public void caseTOpMais(@SuppressWarnings("unused") TOpMais node)
    {
        this.index = 20;
    }

    @Override
    public void caseTOpMenos(@SuppressWarnings("unused") TOpMenos node)
    {
        this.index = 21;
    }

    @Override
    public void caseTOpMult(@SuppressWarnings("unused") TOpMult node)
    {
        this.index = 22;
    }

    @Override
    public void caseTOpDiv(@SuppressWarnings("unused") TOpDiv node)
    {
        this.index = 23;
    }

    @Override
    public void caseTOpMaior(@SuppressWarnings("unused") TOpMaior node)
    {
        this.index = 24;
    }

    @Override
    public void caseTOpMenor(@SuppressWarnings("unused") TOpMenor node)
    {
        this.index = 25;
    }

    @Override
    public void caseTOpMaiorIgual(@SuppressWarnings("unused") TOpMaiorIgual node)
    {
        this.index = 26;
    }

    @Override
    public void caseTOpMenorIgual(@SuppressWarnings("unused") TOpMenorIgual node)
    {
        this.index = 27;
    }

    @Override
    public void caseTOpIgual(@SuppressWarnings("unused") TOpIgual node)
    {
        this.index = 28;
    }

    @Override
    public void caseTOpNao(@SuppressWarnings("unused") TOpNao node)
    {
        this.index = 29;
    }

    @Override
    public void caseTOpE(@SuppressWarnings("unused") TOpE node)
    {
        this.index = 30;
    }

    @Override
    public void caseTOpOu(@SuppressWarnings("unused") TOpOu node)
    {
        this.index = 31;
    }

    @Override
    public void caseTOpAtribuicao(@SuppressWarnings("unused") TOpAtribuicao node)
    {
        this.index = 32;
    }

    @Override
    public void caseTOpRetornoFuncao(@SuppressWarnings("unused") TOpRetornoFuncao node)
    {
        this.index = 33;
    }

    @Override
    public void caseTPonto(@SuppressWarnings("unused") TPonto node)
    {
        this.index = 34;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 35;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 36;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 37;
    }

    @Override
    public void caseTAbreParenteses(@SuppressWarnings("unused") TAbreParenteses node)
    {
        this.index = 38;
    }

    @Override
    public void caseTFechaParenteses(@SuppressWarnings("unused") TFechaParenteses node)
    {
        this.index = 39;
    }

    @Override
    public void caseTAbreColchetes(@SuppressWarnings("unused") TAbreColchetes node)
    {
        this.index = 40;
    }

    @Override
    public void caseTFechaColchetes(@SuppressWarnings("unused") TFechaColchetes node)
    {
        this.index = 41;
    }

    @Override
    public void caseTBarraVertical(@SuppressWarnings("unused") TBarraVertical node)
    {
        this.index = 42;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 43;
    }
}
