/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AAtrib extends PAtrib
{
    private PVar _alvo_;
    private TOpAtribuicao _opAtribuicao_;
    private PExp _valor_;

    public AAtrib()
    {
        // Constructor
    }

    public AAtrib(
        @SuppressWarnings("hiding") PVar _alvo_,
        @SuppressWarnings("hiding") TOpAtribuicao _opAtribuicao_,
        @SuppressWarnings("hiding") PExp _valor_)
    {
        // Constructor
        setAlvo(_alvo_);

        setOpAtribuicao(_opAtribuicao_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AAtrib(
            cloneNode(this._alvo_),
            cloneNode(this._opAtribuicao_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtrib(this);
    }

    public PVar getAlvo()
    {
        return this._alvo_;
    }

    public void setAlvo(PVar node)
    {
        if(this._alvo_ != null)
        {
            this._alvo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alvo_ = node;
    }

    public TOpAtribuicao getOpAtribuicao()
    {
        return this._opAtribuicao_;
    }

    public void setOpAtribuicao(TOpAtribuicao node)
    {
        if(this._opAtribuicao_ != null)
        {
            this._opAtribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opAtribuicao_ = node;
    }

    public PExp getValor()
    {
        return this._valor_;
    }

    public void setValor(PExp node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._alvo_)
            + toString(this._opAtribuicao_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._alvo_ == child)
        {
            this._alvo_ = null;
            return;
        }

        if(this._opAtribuicao_ == child)
        {
            this._opAtribuicao_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._alvo_ == oldChild)
        {
            setAlvo((PVar) newChild);
            return;
        }

        if(this._opAtribuicao_ == oldChild)
        {
            setOpAtribuicao((TOpAtribuicao) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
