/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanoTipoBase extends PTipoBase
{
    private TReservadaBooleano _reservadaBooleano_;

    public ABooleanoTipoBase()
    {
        // Constructor
    }

    public ABooleanoTipoBase(
        @SuppressWarnings("hiding") TReservadaBooleano _reservadaBooleano_)
    {
        // Constructor
        setReservadaBooleano(_reservadaBooleano_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanoTipoBase(
            cloneNode(this._reservadaBooleano_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanoTipoBase(this);
    }

    public TReservadaBooleano getReservadaBooleano()
    {
        return this._reservadaBooleano_;
    }

    public void setReservadaBooleano(TReservadaBooleano node)
    {
        if(this._reservadaBooleano_ != null)
        {
            this._reservadaBooleano_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reservadaBooleano_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reservadaBooleano_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reservadaBooleano_ == child)
        {
            this._reservadaBooleano_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reservadaBooleano_ == oldChild)
        {
            setReservadaBooleano((TReservadaBooleano) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
