/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ACaractereTipoBase extends PTipoBase
{
    private TReservadaCaractere _reservadaCaractere_;

    public ACaractereTipoBase()
    {
        // Constructor
    }

    public ACaractereTipoBase(
        @SuppressWarnings("hiding") TReservadaCaractere _reservadaCaractere_)
    {
        // Constructor
        setReservadaCaractere(_reservadaCaractere_);

    }

    @Override
    public Object clone()
    {
        return new ACaractereTipoBase(
            cloneNode(this._reservadaCaractere_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaractereTipoBase(this);
    }

    public TReservadaCaractere getReservadaCaractere()
    {
        return this._reservadaCaractere_;
    }

    public void setReservadaCaractere(TReservadaCaractere node)
    {
        if(this._reservadaCaractere_ != null)
        {
            this._reservadaCaractere_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reservadaCaractere_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reservadaCaractere_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reservadaCaractere_ == child)
        {
            this._reservadaCaractere_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reservadaCaractere_ == oldChild)
        {
            setReservadaCaractere((TReservadaCaractere) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
