/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AComandoSenao extends PComandoSenao
{
    private TReservadaSenao _reservadaSenao_;
    private PComandoSemSenao _comandoSemSenao_;

    public AComandoSenao()
    {
        // Constructor
    }

    public AComandoSenao(
        @SuppressWarnings("hiding") TReservadaSenao _reservadaSenao_,
        @SuppressWarnings("hiding") PComandoSemSenao _comandoSemSenao_)
    {
        // Constructor
        setReservadaSenao(_reservadaSenao_);

        setComandoSemSenao(_comandoSemSenao_);

    }

    @Override
    public Object clone()
    {
        return new AComandoSenao(
            cloneNode(this._reservadaSenao_),
            cloneNode(this._comandoSemSenao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoSenao(this);
    }

    public TReservadaSenao getReservadaSenao()
    {
        return this._reservadaSenao_;
    }

    public void setReservadaSenao(TReservadaSenao node)
    {
        if(this._reservadaSenao_ != null)
        {
            this._reservadaSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reservadaSenao_ = node;
    }

    public PComandoSemSenao getComandoSemSenao()
    {
        return this._comandoSemSenao_;
    }

    public void setComandoSemSenao(PComandoSemSenao node)
    {
        if(this._comandoSemSenao_ != null)
        {
            this._comandoSemSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSemSenao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reservadaSenao_)
            + toString(this._comandoSemSenao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reservadaSenao_ == child)
        {
            this._reservadaSenao_ = null;
            return;
        }

        if(this._comandoSemSenao_ == child)
        {
            this._comandoSemSenao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reservadaSenao_ == oldChild)
        {
            setReservadaSenao((TReservadaSenao) newChild);
            return;
        }

        if(this._comandoSemSenao_ == oldChild)
        {
            setComandoSemSenao((PComandoSemSenao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
