/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ADivisaoExpMultiplicativaCauda extends PExpMultiplicativaCauda
{
    private TOpDiv _opDiv_;
    private PExpUnaria _right_;

    public ADivisaoExpMultiplicativaCauda()
    {
        // Constructor
    }

    public ADivisaoExpMultiplicativaCauda(
        @SuppressWarnings("hiding") TOpDiv _opDiv_,
        @SuppressWarnings("hiding") PExpUnaria _right_)
    {
        // Constructor
        setOpDiv(_opDiv_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ADivisaoExpMultiplicativaCauda(
            cloneNode(this._opDiv_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivisaoExpMultiplicativaCauda(this);
    }

    public TOpDiv getOpDiv()
    {
        return this._opDiv_;
    }

    public void setOpDiv(TOpDiv node)
    {
        if(this._opDiv_ != null)
        {
            this._opDiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opDiv_ = node;
    }

    public PExpUnaria getRight()
    {
        return this._right_;
    }

    public void setRight(PExpUnaria node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opDiv_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opDiv_ == child)
        {
            this._opDiv_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opDiv_ == oldChild)
        {
            setOpDiv((TOpDiv) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpUnaria) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
