/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AEnquantoComando extends PComando
{
    private TReservadaEnquanto _reservadaEnquanto_;
    private TAbreParenteses _abreParenteses_;
    private PExp _exp_;
    private TFechaParenteses _fechaParenteses_;
    private PComandoSemSenao _comandoSemSenao_;

    public AEnquantoComando()
    {
        // Constructor
    }

    public AEnquantoComando(
        @SuppressWarnings("hiding") TReservadaEnquanto _reservadaEnquanto_,
        @SuppressWarnings("hiding") TAbreParenteses _abreParenteses_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TFechaParenteses _fechaParenteses_,
        @SuppressWarnings("hiding") PComandoSemSenao _comandoSemSenao_)
    {
        // Constructor
        setReservadaEnquanto(_reservadaEnquanto_);

        setAbreParenteses(_abreParenteses_);

        setExp(_exp_);

        setFechaParenteses(_fechaParenteses_);

        setComandoSemSenao(_comandoSemSenao_);

    }

    @Override
    public Object clone()
    {
        return new AEnquantoComando(
            cloneNode(this._reservadaEnquanto_),
            cloneNode(this._abreParenteses_),
            cloneNode(this._exp_),
            cloneNode(this._fechaParenteses_),
            cloneNode(this._comandoSemSenao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnquantoComando(this);
    }

    public TReservadaEnquanto getReservadaEnquanto()
    {
        return this._reservadaEnquanto_;
    }

    public void setReservadaEnquanto(TReservadaEnquanto node)
    {
        if(this._reservadaEnquanto_ != null)
        {
            this._reservadaEnquanto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reservadaEnquanto_ = node;
    }

    public TAbreParenteses getAbreParenteses()
    {
        return this._abreParenteses_;
    }

    public void setAbreParenteses(TAbreParenteses node)
    {
        if(this._abreParenteses_ != null)
        {
            this._abreParenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreParenteses_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TFechaParenteses getFechaParenteses()
    {
        return this._fechaParenteses_;
    }

    public void setFechaParenteses(TFechaParenteses node)
    {
        if(this._fechaParenteses_ != null)
        {
            this._fechaParenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaParenteses_ = node;
    }

    public PComandoSemSenao getComandoSemSenao()
    {
        return this._comandoSemSenao_;
    }

    public void setComandoSemSenao(PComandoSemSenao node)
    {
        if(this._comandoSemSenao_ != null)
        {
            this._comandoSemSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSemSenao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reservadaEnquanto_)
            + toString(this._abreParenteses_)
            + toString(this._exp_)
            + toString(this._fechaParenteses_)
            + toString(this._comandoSemSenao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reservadaEnquanto_ == child)
        {
            this._reservadaEnquanto_ = null;
            return;
        }

        if(this._abreParenteses_ == child)
        {
            this._abreParenteses_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._fechaParenteses_ == child)
        {
            this._fechaParenteses_ = null;
            return;
        }

        if(this._comandoSemSenao_ == child)
        {
            this._comandoSemSenao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reservadaEnquanto_ == oldChild)
        {
            setReservadaEnquanto((TReservadaEnquanto) newChild);
            return;
        }

        if(this._abreParenteses_ == oldChild)
        {
            setAbreParenteses((TAbreParenteses) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._fechaParenteses_ == oldChild)
        {
            setFechaParenteses((TFechaParenteses) newChild);
            return;
        }

        if(this._comandoSemSenao_ == oldChild)
        {
            setComandoSemSenao((PComandoSemSenao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
