/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpE extends PExpE
{
    private PExpIgualdade _left_;
    private final LinkedList<PExpECauda> _expECauda_ = new LinkedList<PExpECauda>();

    public AExpE()
    {
        // Constructor
    }

    public AExpE(
        @SuppressWarnings("hiding") PExpIgualdade _left_,
        @SuppressWarnings("hiding") List<?> _expECauda_)
    {
        // Constructor
        setLeft(_left_);

        setExpECauda(_expECauda_);

    }

    @Override
    public Object clone()
    {
        return new AExpE(
            cloneNode(this._left_),
            cloneList(this._expECauda_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpE(this);
    }

    public PExpIgualdade getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpIgualdade node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public LinkedList<PExpECauda> getExpECauda()
    {
        return this._expECauda_;
    }

    public void setExpECauda(List<?> list)
    {
        for(PExpECauda e : this._expECauda_)
        {
            e.parent(null);
        }
        this._expECauda_.clear();

        for(Object obj_e : list)
        {
            PExpECauda e = (PExpECauda) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expECauda_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._expECauda_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._expECauda_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExpIgualdade) newChild);
            return;
        }

        for(ListIterator<PExpECauda> i = this._expECauda_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpECauda) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
