/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpECauda extends PExpECauda
{
    private TOpE _opE_;
    private PExpIgualdade _right_;

    public AExpECauda()
    {
        // Constructor
    }

    public AExpECauda(
        @SuppressWarnings("hiding") TOpE _opE_,
        @SuppressWarnings("hiding") PExpIgualdade _right_)
    {
        // Constructor
        setOpE(_opE_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AExpECauda(
            cloneNode(this._opE_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpECauda(this);
    }

    public TOpE getOpE()
    {
        return this._opE_;
    }

    public void setOpE(TOpE node)
    {
        if(this._opE_ != null)
        {
            this._opE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opE_ = node;
    }

    public PExpIgualdade getRight()
    {
        return this._right_;
    }

    public void setRight(PExpIgualdade node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opE_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opE_ == child)
        {
            this._opE_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opE_ == oldChild)
        {
            setOpE((TOpE) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpIgualdade) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
