/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpOu extends PExpOu
{
    private PExpE _left_;
    private final LinkedList<PExpOuCauda> _expOuCauda_ = new LinkedList<PExpOuCauda>();

    public AExpOu()
    {
        // Constructor
    }

    public AExpOu(
        @SuppressWarnings("hiding") PExpE _left_,
        @SuppressWarnings("hiding") List<?> _expOuCauda_)
    {
        // Constructor
        setLeft(_left_);

        setExpOuCauda(_expOuCauda_);

    }

    @Override
    public Object clone()
    {
        return new AExpOu(
            cloneNode(this._left_),
            cloneList(this._expOuCauda_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpOu(this);
    }

    public PExpE getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpE node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public LinkedList<PExpOuCauda> getExpOuCauda()
    {
        return this._expOuCauda_;
    }

    public void setExpOuCauda(List<?> list)
    {
        for(PExpOuCauda e : this._expOuCauda_)
        {
            e.parent(null);
        }
        this._expOuCauda_.clear();

        for(Object obj_e : list)
        {
            PExpOuCauda e = (PExpOuCauda) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expOuCauda_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._expOuCauda_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._expOuCauda_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExpE) newChild);
            return;
        }

        for(ListIterator<PExpOuCauda> i = this._expOuCauda_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpOuCauda) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
