/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpOuCauda extends PExpOuCauda
{
    private TOpOu _opOu_;
    private PExpE _right_;

    public AExpOuCauda()
    {
        // Constructor
    }

    public AExpOuCauda(
        @SuppressWarnings("hiding") TOpOu _opOu_,
        @SuppressWarnings("hiding") PExpE _right_)
    {
        // Constructor
        setOpOu(_opOu_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AExpOuCauda(
            cloneNode(this._opOu_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpOuCauda(this);
    }

    public TOpOu getOpOu()
    {
        return this._opOu_;
    }

    public void setOpOu(TOpOu node)
    {
        if(this._opOu_ != null)
        {
            this._opOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opOu_ = node;
    }

    public PExpE getRight()
    {
        return this._right_;
    }

    public void setRight(PExpE node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opOu_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opOu_ == child)
        {
            this._opOu_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opOu_ == oldChild)
        {
            setOpOu((TOpOu) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
