/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpAditiva extends PExpAditiva
{
    private PExpMultiplicativa _left_;
    private final LinkedList<PExpAditivaCauda> _expAditivaCauda_ = new LinkedList<PExpAditivaCauda>();

    public AExpAditiva()
    {
        // Constructor
    }

    public AExpAditiva(
        @SuppressWarnings("hiding") PExpMultiplicativa _left_,
        @SuppressWarnings("hiding") List<?> _expAditivaCauda_)
    {
        // Constructor
        setLeft(_left_);

        setExpAditivaCauda(_expAditivaCauda_);

    }

    @Override
    public Object clone()
    {
        return new AExpAditiva(
            cloneNode(this._left_),
            cloneList(this._expAditivaCauda_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpAditiva(this);
    }

    public PExpMultiplicativa getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpMultiplicativa node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public LinkedList<PExpAditivaCauda> getExpAditivaCauda()
    {
        return this._expAditivaCauda_;
    }

    public void setExpAditivaCauda(List<?> list)
    {
        for(PExpAditivaCauda e : this._expAditivaCauda_)
        {
            e.parent(null);
        }
        this._expAditivaCauda_.clear();

        for(Object obj_e : list)
        {
            PExpAditivaCauda e = (PExpAditivaCauda) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expAditivaCauda_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._expAditivaCauda_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._expAditivaCauda_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExpMultiplicativa) newChild);
            return;
        }

        for(ListIterator<PExpAditivaCauda> i = this._expAditivaCauda_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpAditivaCauda) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
