/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExp extends PExp
{
    private PExpOu _expOu_;

    public AExp()
    {
        // Constructor
    }

    public AExp(
        @SuppressWarnings("hiding") PExpOu _expOu_)
    {
        // Constructor
        setExpOu(_expOu_);

    }

    @Override
    public Object clone()
    {
        return new AExp(
            cloneNode(this._expOu_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp(this);
    }

    public PExpOu getExpOu()
    {
        return this._expOu_;
    }

    public void setExpOu(PExpOu node)
    {
        if(this._expOu_ != null)
        {
            this._expOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOu_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOu_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOu_ == child)
        {
            this._expOu_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOu_ == oldChild)
        {
            setExpOu((PExpOu) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
