/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpMultiplicativa extends PExpMultiplicativa
{
    private PExpUnaria _left_;
    private final LinkedList<PExpMultiplicativaCauda> _expMultiplicativaCauda_ = new LinkedList<PExpMultiplicativaCauda>();

    public AExpMultiplicativa()
    {
        // Constructor
    }

    public AExpMultiplicativa(
        @SuppressWarnings("hiding") PExpUnaria _left_,
        @SuppressWarnings("hiding") List<?> _expMultiplicativaCauda_)
    {
        // Constructor
        setLeft(_left_);

        setExpMultiplicativaCauda(_expMultiplicativaCauda_);

    }

    @Override
    public Object clone()
    {
        return new AExpMultiplicativa(
            cloneNode(this._left_),
            cloneList(this._expMultiplicativaCauda_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMultiplicativa(this);
    }

    public PExpUnaria getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpUnaria node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public LinkedList<PExpMultiplicativaCauda> getExpMultiplicativaCauda()
    {
        return this._expMultiplicativaCauda_;
    }

    public void setExpMultiplicativaCauda(List<?> list)
    {
        for(PExpMultiplicativaCauda e : this._expMultiplicativaCauda_)
        {
            e.parent(null);
        }
        this._expMultiplicativaCauda_.clear();

        for(Object obj_e : list)
        {
            PExpMultiplicativaCauda e = (PExpMultiplicativaCauda) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expMultiplicativaCauda_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._expMultiplicativaCauda_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._expMultiplicativaCauda_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExpUnaria) newChild);
            return;
        }

        for(ListIterator<PExpMultiplicativaCauda> i = this._expMultiplicativaCauda_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpMultiplicativaCauda) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
