/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ALerComandoSimples extends PComandoSimples
{
    private TReservadaLer _reservadaLer_;
    private TAbreParenteses _abreParenteses_;
    private PListaVar _listaVar_;
    private TFechaParenteses _fechaParenteses_;
    private TPonto _ponto_;

    public ALerComandoSimples()
    {
        // Constructor
    }

    public ALerComandoSimples(
        @SuppressWarnings("hiding") TReservadaLer _reservadaLer_,
        @SuppressWarnings("hiding") TAbreParenteses _abreParenteses_,
        @SuppressWarnings("hiding") PListaVar _listaVar_,
        @SuppressWarnings("hiding") TFechaParenteses _fechaParenteses_,
        @SuppressWarnings("hiding") TPonto _ponto_)
    {
        // Constructor
        setReservadaLer(_reservadaLer_);

        setAbreParenteses(_abreParenteses_);

        setListaVar(_listaVar_);

        setFechaParenteses(_fechaParenteses_);

        setPonto(_ponto_);

    }

    @Override
    public Object clone()
    {
        return new ALerComandoSimples(
            cloneNode(this._reservadaLer_),
            cloneNode(this._abreParenteses_),
            cloneNode(this._listaVar_),
            cloneNode(this._fechaParenteses_),
            cloneNode(this._ponto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALerComandoSimples(this);
    }

    public TReservadaLer getReservadaLer()
    {
        return this._reservadaLer_;
    }

    public void setReservadaLer(TReservadaLer node)
    {
        if(this._reservadaLer_ != null)
        {
            this._reservadaLer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reservadaLer_ = node;
    }

    public TAbreParenteses getAbreParenteses()
    {
        return this._abreParenteses_;
    }

    public void setAbreParenteses(TAbreParenteses node)
    {
        if(this._abreParenteses_ != null)
        {
            this._abreParenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreParenteses_ = node;
    }

    public PListaVar getListaVar()
    {
        return this._listaVar_;
    }

    public void setListaVar(PListaVar node)
    {
        if(this._listaVar_ != null)
        {
            this._listaVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaVar_ = node;
    }

    public TFechaParenteses getFechaParenteses()
    {
        return this._fechaParenteses_;
    }

    public void setFechaParenteses(TFechaParenteses node)
    {
        if(this._fechaParenteses_ != null)
        {
            this._fechaParenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaParenteses_ = node;
    }

    public TPonto getPonto()
    {
        return this._ponto_;
    }

    public void setPonto(TPonto node)
    {
        if(this._ponto_ != null)
        {
            this._ponto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ponto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reservadaLer_)
            + toString(this._abreParenteses_)
            + toString(this._listaVar_)
            + toString(this._fechaParenteses_)
            + toString(this._ponto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reservadaLer_ == child)
        {
            this._reservadaLer_ = null;
            return;
        }

        if(this._abreParenteses_ == child)
        {
            this._abreParenteses_ = null;
            return;
        }

        if(this._listaVar_ == child)
        {
            this._listaVar_ = null;
            return;
        }

        if(this._fechaParenteses_ == child)
        {
            this._fechaParenteses_ = null;
            return;
        }

        if(this._ponto_ == child)
        {
            this._ponto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reservadaLer_ == oldChild)
        {
            setReservadaLer((TReservadaLer) newChild);
            return;
        }

        if(this._abreParenteses_ == oldChild)
        {
            setAbreParenteses((TAbreParenteses) newChild);
            return;
        }

        if(this._listaVar_ == oldChild)
        {
            setListaVar((PListaVar) newChild);
            return;
        }

        if(this._fechaParenteses_ == oldChild)
        {
            setFechaParenteses((TFechaParenteses) newChild);
            return;
        }

        if(this._ponto_ == oldChild)
        {
            setPonto((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
