/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AListaVar extends PListaVar
{
    private PVar _var_;
    private final LinkedList<PListaVarCauda> _listaVarCauda_ = new LinkedList<PListaVarCauda>();

    public AListaVar()
    {
        // Constructor
    }

    public AListaVar(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") List<?> _listaVarCauda_)
    {
        // Constructor
        setVar(_var_);

        setListaVarCauda(_listaVarCauda_);

    }

    @Override
    public Object clone()
    {
        return new AListaVar(
            cloneNode(this._var_),
            cloneList(this._listaVarCauda_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaVar(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public LinkedList<PListaVarCauda> getListaVarCauda()
    {
        return this._listaVarCauda_;
    }

    public void setListaVarCauda(List<?> list)
    {
        for(PListaVarCauda e : this._listaVarCauda_)
        {
            e.parent(null);
        }
        this._listaVarCauda_.clear();

        for(Object obj_e : list)
        {
            PListaVarCauda e = (PListaVarCauda) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._listaVarCauda_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._listaVarCauda_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._listaVarCauda_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        for(ListIterator<PListaVarCauda> i = this._listaVarCauda_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PListaVarCauda) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
