/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AListaAtrib extends PListaAtrib
{
    private PAtrib _atrib_;
    private final LinkedList<PListaAtribCauda> _listaAtribCauda_ = new LinkedList<PListaAtribCauda>();

    public AListaAtrib()
    {
        // Constructor
    }

    public AListaAtrib(
        @SuppressWarnings("hiding") PAtrib _atrib_,
        @SuppressWarnings("hiding") List<?> _listaAtribCauda_)
    {
        // Constructor
        setAtrib(_atrib_);

        setListaAtribCauda(_listaAtribCauda_);

    }

    @Override
    public Object clone()
    {
        return new AListaAtrib(
            cloneNode(this._atrib_),
            cloneList(this._listaAtribCauda_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaAtrib(this);
    }

    public PAtrib getAtrib()
    {
        return this._atrib_;
    }

    public void setAtrib(PAtrib node)
    {
        if(this._atrib_ != null)
        {
            this._atrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atrib_ = node;
    }

    public LinkedList<PListaAtribCauda> getListaAtribCauda()
    {
        return this._listaAtribCauda_;
    }

    public void setListaAtribCauda(List<?> list)
    {
        for(PListaAtribCauda e : this._listaAtribCauda_)
        {
            e.parent(null);
        }
        this._listaAtribCauda_.clear();

        for(Object obj_e : list)
        {
            PListaAtribCauda e = (PListaAtribCauda) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._listaAtribCauda_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atrib_)
            + toString(this._listaAtribCauda_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atrib_ == child)
        {
            this._atrib_ = null;
            return;
        }

        if(this._listaAtribCauda_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atrib_ == oldChild)
        {
            setAtrib((PAtrib) newChild);
            return;
        }

        for(ListIterator<PListaAtribCauda> i = this._listaAtribCauda_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PListaAtribCauda) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
