/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AListaNomes extends PListaNomes
{
    private TIdentificador _identificador_;
    private final LinkedList<PListaNomesCauda> _listaNomesCauda_ = new LinkedList<PListaNomesCauda>();

    public AListaNomes()
    {
        // Constructor
    }

    public AListaNomes(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") List<?> _listaNomesCauda_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setListaNomesCauda(_listaNomesCauda_);

    }

    @Override
    public Object clone()
    {
        return new AListaNomes(
            cloneNode(this._identificador_),
            cloneList(this._listaNomesCauda_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaNomes(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public LinkedList<PListaNomesCauda> getListaNomesCauda()
    {
        return this._listaNomesCauda_;
    }

    public void setListaNomesCauda(List<?> list)
    {
        for(PListaNomesCauda e : this._listaNomesCauda_)
        {
            e.parent(null);
        }
        this._listaNomesCauda_.clear();

        for(Object obj_e : list)
        {
            PListaNomesCauda e = (PListaNomesCauda) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._listaNomesCauda_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._listaNomesCauda_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._listaNomesCauda_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        for(ListIterator<PListaNomesCauda> i = this._listaNomesCauda_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PListaNomesCauda) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
