/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AListaExp extends PListaExp
{
    private PExp _exp_;
    private final LinkedList<PListaExpCauda> _listaExpCauda_ = new LinkedList<PListaExpCauda>();

    public AListaExp()
    {
        // Constructor
    }

    public AListaExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") List<?> _listaExpCauda_)
    {
        // Constructor
        setExp(_exp_);

        setListaExpCauda(_listaExpCauda_);

    }

    @Override
    public Object clone()
    {
        return new AListaExp(
            cloneNode(this._exp_),
            cloneList(this._listaExpCauda_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public LinkedList<PListaExpCauda> getListaExpCauda()
    {
        return this._listaExpCauda_;
    }

    public void setListaExpCauda(List<?> list)
    {
        for(PListaExpCauda e : this._listaExpCauda_)
        {
            e.parent(null);
        }
        this._listaExpCauda_.clear();

        for(Object obj_e : list)
        {
            PListaExpCauda e = (PListaExpCauda) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._listaExpCauda_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._listaExpCauda_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._listaExpCauda_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        for(ListIterator<PListaExpCauda> i = this._listaExpCauda_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PListaExpCauda) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
