/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorIgualExpRelacionalCauda extends PExpRelacionalCauda
{
    private TOpMaiorIgual _opMaiorIgual_;
    private PExpAditiva _right_;

    public AMaiorIgualExpRelacionalCauda()
    {
        // Constructor
    }

    public AMaiorIgualExpRelacionalCauda(
        @SuppressWarnings("hiding") TOpMaiorIgual _opMaiorIgual_,
        @SuppressWarnings("hiding") PExpAditiva _right_)
    {
        // Constructor
        setOpMaiorIgual(_opMaiorIgual_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorIgualExpRelacionalCauda(
            cloneNode(this._opMaiorIgual_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorIgualExpRelacionalCauda(this);
    }

    public TOpMaiorIgual getOpMaiorIgual()
    {
        return this._opMaiorIgual_;
    }

    public void setOpMaiorIgual(TOpMaiorIgual node)
    {
        if(this._opMaiorIgual_ != null)
        {
            this._opMaiorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opMaiorIgual_ = node;
    }

    public PExpAditiva getRight()
    {
        return this._right_;
    }

    public void setRight(PExpAditiva node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opMaiorIgual_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opMaiorIgual_ == child)
        {
            this._opMaiorIgual_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opMaiorIgual_ == oldChild)
        {
            setOpMaiorIgual((TOpMaiorIgual) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpAditiva) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
