/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorExpRelacionalCauda extends PExpRelacionalCauda
{
    private TOpMaior _opMaior_;
    private PExpAditiva _right_;

    public AMaiorExpRelacionalCauda()
    {
        // Constructor
    }

    public AMaiorExpRelacionalCauda(
        @SuppressWarnings("hiding") TOpMaior _opMaior_,
        @SuppressWarnings("hiding") PExpAditiva _right_)
    {
        // Constructor
        setOpMaior(_opMaior_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorExpRelacionalCauda(
            cloneNode(this._opMaior_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorExpRelacionalCauda(this);
    }

    public TOpMaior getOpMaior()
    {
        return this._opMaior_;
    }

    public void setOpMaior(TOpMaior node)
    {
        if(this._opMaior_ != null)
        {
            this._opMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opMaior_ = node;
    }

    public PExpAditiva getRight()
    {
        return this._right_;
    }

    public void setRight(PExpAditiva node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opMaior_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opMaior_ == child)
        {
            this._opMaior_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opMaior_ == oldChild)
        {
            setOpMaior((TOpMaior) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpAditiva) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
