/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AMenorExpRelacionalCauda extends PExpRelacionalCauda
{
    private TOpMenor _opMenor_;
    private PExpAditiva _right_;

    public AMenorExpRelacionalCauda()
    {
        // Constructor
    }

    public AMenorExpRelacionalCauda(
        @SuppressWarnings("hiding") TOpMenor _opMenor_,
        @SuppressWarnings("hiding") PExpAditiva _right_)
    {
        // Constructor
        setOpMenor(_opMenor_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AMenorExpRelacionalCauda(
            cloneNode(this._opMenor_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorExpRelacionalCauda(this);
    }

    public TOpMenor getOpMenor()
    {
        return this._opMenor_;
    }

    public void setOpMenor(TOpMenor node)
    {
        if(this._opMenor_ != null)
        {
            this._opMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opMenor_ = node;
    }

    public PExpAditiva getRight()
    {
        return this._right_;
    }

    public void setRight(PExpAditiva node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opMenor_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opMenor_ == child)
        {
            this._opMenor_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opMenor_ == oldChild)
        {
            setOpMenor((TOpMenor) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpAditiva) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
