/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANumeroTipoBase extends PTipoBase
{
    private TReservadaNumero _reservadaNumero_;

    public ANumeroTipoBase()
    {
        // Constructor
    }

    public ANumeroTipoBase(
        @SuppressWarnings("hiding") TReservadaNumero _reservadaNumero_)
    {
        // Constructor
        setReservadaNumero(_reservadaNumero_);

    }

    @Override
    public Object clone()
    {
        return new ANumeroTipoBase(
            cloneNode(this._reservadaNumero_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumeroTipoBase(this);
    }

    public TReservadaNumero getReservadaNumero()
    {
        return this._reservadaNumero_;
    }

    public void setReservadaNumero(TReservadaNumero node)
    {
        if(this._reservadaNumero_ != null)
        {
            this._reservadaNumero_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reservadaNumero_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reservadaNumero_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reservadaNumero_ == child)
        {
            this._reservadaNumero_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reservadaNumero_ == oldChild)
        {
            setReservadaNumero((TReservadaNumero) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
