/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AParametroCauda extends PParametroCauda
{
    private TBarraVertical _barraVertical_;
    private PParametro _parametro_;

    public AParametroCauda()
    {
        // Constructor
    }

    public AParametroCauda(
        @SuppressWarnings("hiding") TBarraVertical _barraVertical_,
        @SuppressWarnings("hiding") PParametro _parametro_)
    {
        // Constructor
        setBarraVertical(_barraVertical_);

        setParametro(_parametro_);

    }

    @Override
    public Object clone()
    {
        return new AParametroCauda(
            cloneNode(this._barraVertical_),
            cloneNode(this._parametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametroCauda(this);
    }

    public TBarraVertical getBarraVertical()
    {
        return this._barraVertical_;
    }

    public void setBarraVertical(TBarraVertical node)
    {
        if(this._barraVertical_ != null)
        {
            this._barraVertical_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._barraVertical_ = node;
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._barraVertical_)
            + toString(this._parametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._barraVertical_ == child)
        {
            this._barraVertical_ = null;
            return;
        }

        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._barraVertical_ == oldChild)
        {
            setBarraVertical((TBarraVertical) newChild);
            return;
        }

        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
