/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class APrimariaExpUnaria extends PExpUnaria
{
    private PExpPrimaria _expPrimaria_;

    public APrimariaExpUnaria()
    {
        // Constructor
    }

    public APrimariaExpUnaria(
        @SuppressWarnings("hiding") PExpPrimaria _expPrimaria_)
    {
        // Constructor
        setExpPrimaria(_expPrimaria_);

    }

    @Override
    public Object clone()
    {
        return new APrimariaExpUnaria(
            cloneNode(this._expPrimaria_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimariaExpUnaria(this);
    }

    public PExpPrimaria getExpPrimaria()
    {
        return this._expPrimaria_;
    }

    public void setExpPrimaria(PExpPrimaria node)
    {
        if(this._expPrimaria_ != null)
        {
            this._expPrimaria_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expPrimaria_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expPrimaria_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expPrimaria_ == child)
        {
            this._expPrimaria_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expPrimaria_ == oldChild)
        {
            setExpPrimaria((PExpPrimaria) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
