/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ARetorneComandoSimples extends PComandoSimples
{
    private TReservadaRetorne _reservadaRetorne_;
    private PExp _valor_;
    private TPonto _ponto_;

    public ARetorneComandoSimples()
    {
        // Constructor
    }

    public ARetorneComandoSimples(
        @SuppressWarnings("hiding") TReservadaRetorne _reservadaRetorne_,
        @SuppressWarnings("hiding") PExp _valor_,
        @SuppressWarnings("hiding") TPonto _ponto_)
    {
        // Constructor
        setReservadaRetorne(_reservadaRetorne_);

        setValor(_valor_);

        setPonto(_ponto_);

    }

    @Override
    public Object clone()
    {
        return new ARetorneComandoSimples(
            cloneNode(this._reservadaRetorne_),
            cloneNode(this._valor_),
            cloneNode(this._ponto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARetorneComandoSimples(this);
    }

    public TReservadaRetorne getReservadaRetorne()
    {
        return this._reservadaRetorne_;
    }

    public void setReservadaRetorne(TReservadaRetorne node)
    {
        if(this._reservadaRetorne_ != null)
        {
            this._reservadaRetorne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reservadaRetorne_ = node;
    }

    public PExp getValor()
    {
        return this._valor_;
    }

    public void setValor(PExp node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    public TPonto getPonto()
    {
        return this._ponto_;
    }

    public void setPonto(TPonto node)
    {
        if(this._ponto_ != null)
        {
            this._ponto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ponto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reservadaRetorne_)
            + toString(this._valor_)
            + toString(this._ponto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reservadaRetorne_ == child)
        {
            this._reservadaRetorne_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        if(this._ponto_ == child)
        {
            this._ponto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reservadaRetorne_ == oldChild)
        {
            setReservadaRetorne((TReservadaRetorne) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PExp) newChild);
            return;
        }

        if(this._ponto_ == oldChild)
        {
            setPonto((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
