/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class ASimplesVar extends PVar
{
    private TIdentificador _identificador_;
    private final LinkedList<PVarIndexada> _varIndexada_ = new LinkedList<PVarIndexada>();

    public ASimplesVar()
    {
        // Constructor
    }

    public ASimplesVar(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") List<?> _varIndexada_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setVarIndexada(_varIndexada_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesVar(
            cloneNode(this._identificador_),
            cloneList(this._varIndexada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesVar(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public LinkedList<PVarIndexada> getVarIndexada()
    {
        return this._varIndexada_;
    }

    public void setVarIndexada(List<?> list)
    {
        for(PVarIndexada e : this._varIndexada_)
        {
            e.parent(null);
        }
        this._varIndexada_.clear();

        for(Object obj_e : list)
        {
            PVarIndexada e = (PVarIndexada) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._varIndexada_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._varIndexada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._varIndexada_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        for(ListIterator<PVarIndexada> i = this._varIndexada_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVarIndexada) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
