/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ASomaExpAditivaCauda extends PExpAditivaCauda
{
    private TOpMais _opMais_;
    private PExpMultiplicativa _right_;

    public ASomaExpAditivaCauda()
    {
        // Constructor
    }

    public ASomaExpAditivaCauda(
        @SuppressWarnings("hiding") TOpMais _opMais_,
        @SuppressWarnings("hiding") PExpMultiplicativa _right_)
    {
        // Constructor
        setOpMais(_opMais_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ASomaExpAditivaCauda(
            cloneNode(this._opMais_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaExpAditivaCauda(this);
    }

    public TOpMais getOpMais()
    {
        return this._opMais_;
    }

    public void setOpMais(TOpMais node)
    {
        if(this._opMais_ != null)
        {
            this._opMais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opMais_ = node;
    }

    public PExpMultiplicativa getRight()
    {
        return this._right_;
    }

    public void setRight(PExpMultiplicativa node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opMais_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opMais_ == child)
        {
            this._opMais_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opMais_ == oldChild)
        {
            setOpMais((TOpMais) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpMultiplicativa) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
