/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AVazioTipoRetorno extends PTipoRetorno
{
    private TReservadaVazio _reservadaVazio_;

    public AVazioTipoRetorno()
    {
        // Constructor
    }

    public AVazioTipoRetorno(
        @SuppressWarnings("hiding") TReservadaVazio _reservadaVazio_)
    {
        // Constructor
        setReservadaVazio(_reservadaVazio_);

    }

    @Override
    public Object clone()
    {
        return new AVazioTipoRetorno(
            cloneNode(this._reservadaVazio_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioTipoRetorno(this);
    }

    public TReservadaVazio getReservadaVazio()
    {
        return this._reservadaVazio_;
    }

    public void setReservadaVazio(TReservadaVazio node)
    {
        if(this._reservadaVazio_ != null)
        {
            this._reservadaVazio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reservadaVazio_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reservadaVazio_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reservadaVazio_ == child)
        {
            this._reservadaVazio_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reservadaVazio_ == oldChild)
        {
            setReservadaVazio((TReservadaVazio) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
