/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AVetorTipo extends PTipo
{
    private TReservadaVetor _reservadaVetor_;
    private PTipoBase _tipoBase_;
    private final LinkedList<PVetorDimensoes> _vetorDimensoes_ = new LinkedList<PVetorDimensoes>();

    public AVetorTipo()
    {
        // Constructor
    }

    public AVetorTipo(
        @SuppressWarnings("hiding") TReservadaVetor _reservadaVetor_,
        @SuppressWarnings("hiding") PTipoBase _tipoBase_,
        @SuppressWarnings("hiding") List<?> _vetorDimensoes_)
    {
        // Constructor
        setReservadaVetor(_reservadaVetor_);

        setTipoBase(_tipoBase_);

        setVetorDimensoes(_vetorDimensoes_);

    }

    @Override
    public Object clone()
    {
        return new AVetorTipo(
            cloneNode(this._reservadaVetor_),
            cloneNode(this._tipoBase_),
            cloneList(this._vetorDimensoes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVetorTipo(this);
    }

    public TReservadaVetor getReservadaVetor()
    {
        return this._reservadaVetor_;
    }

    public void setReservadaVetor(TReservadaVetor node)
    {
        if(this._reservadaVetor_ != null)
        {
            this._reservadaVetor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reservadaVetor_ = node;
    }

    public PTipoBase getTipoBase()
    {
        return this._tipoBase_;
    }

    public void setTipoBase(PTipoBase node)
    {
        if(this._tipoBase_ != null)
        {
            this._tipoBase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoBase_ = node;
    }

    public LinkedList<PVetorDimensoes> getVetorDimensoes()
    {
        return this._vetorDimensoes_;
    }

    public void setVetorDimensoes(List<?> list)
    {
        for(PVetorDimensoes e : this._vetorDimensoes_)
        {
            e.parent(null);
        }
        this._vetorDimensoes_.clear();

        for(Object obj_e : list)
        {
            PVetorDimensoes e = (PVetorDimensoes) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._vetorDimensoes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reservadaVetor_)
            + toString(this._tipoBase_)
            + toString(this._vetorDimensoes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reservadaVetor_ == child)
        {
            this._reservadaVetor_ = null;
            return;
        }

        if(this._tipoBase_ == child)
        {
            this._tipoBase_ = null;
            return;
        }

        if(this._vetorDimensoes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reservadaVetor_ == oldChild)
        {
            setReservadaVetor((TReservadaVetor) newChild);
            return;
        }

        if(this._tipoBase_ == oldChild)
        {
            setTipoBase((PTipoBase) newChild);
            return;
        }

        for(ListIterator<PVetorDimensoes> i = this._vetorDimensoes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVetorDimensoes) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
