/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class TReservadaCaractere extends Token
{
    public TReservadaCaractere()
    {
        super.setText("caractere");
    }

    public TReservadaCaractere(int line, int pos)
    {
        super.setText("caractere");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReservadaCaractere(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReservadaCaractere(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReservadaCaractere text.");
    }
}
